plugin.plugin_configuration.search_api_backend.search_api_europa_search:
  type: plugin.plugin_configuration.search_api_backend.*
  label: 'EC Europa Search settings'
  mapping:
    api_key:
      type: string
      label: 'API key'
    enable_ingestion:
      type: boolean
      label: 'Enable ingestion'
    database:
      type: string
      label: 'Database'
    text_ingestion_api_endpoint:
      type: string
      label: 'Text ingestion API endpoint URL'
    file_ingestion_api_endpoint:
      type: string
      label: 'File ingestion API endpoint URL'
    delete_api_endpoint:
      type: string
      label: 'Delete API endpoint URL'
    token_api_endpoint:
      type: string
      label: 'Token API endpoint URL'
    search_api_endpoint:
      type: string
      label: 'Search API endpoint URL'
    facets_api_endpoint:
      type: string
      label: 'Facets API endpoint URL'
    info_api_endpoint:
      type: string
      label: 'Info API endpoint URL'
