plugin.plugin_configuration.search_api_backend.search_api_europa_search:
  type: plugin.plugin_configuration.search_api_backend.*
  label: 'EC Europa Search settings'
  mapping:
    api_key:
      type: string
      label: 'API key'
    database:
      type: string
      label: 'Database'
    ingestion_api_endpoint:
      type: string
      label: 'Ingestion API endpoint URL'
    search_api_endpoint:
      type: string
      label: 'Search API endpoint URL'
    token_api_endpoint:
      type: string
      label: 'Token API endpoint URL'
