plugin.plugin_configuration.search_api_backend.oe_search_enterprise_search:
  type: config_object
  label: 'EC Enterprise Search settings'
  mapping:
    api_key:
      type: string
      label: 'API key'
    database:
      type: string
      label: 'Database'
    ingestion_api_endpoint:
      type: string
      label: 'Ingestion API endpoint URL'
    search_api_endpoint:
      type: string
      label: 'Search API endpoint URL'
